name: Disease Alert

on:
  push:
    branches: main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 20

      # ... rest of the workflow ...

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Choose the appropriate version

      - name: Upload Package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-artifacts
          path: path/to/main.py

      - name: Make package available for download
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: path/to/utils.py
dancerist
Gian Collin Gesta
name: Disease Alert

on:
  push:
    branches: main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 20

      # ... rest of the workflow ...

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Choose the appropriate version

      - name: Upload Package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-artifacts
          path: path/to/main.py

      
